services:
  - type: web
    name: tradeai-companion
    runtime: python3
    plan: starter
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TELEGRAM_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_API_SECRET
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: CHART_IMG_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tradeai-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: .
      - key: TZ
        value: UTC
      - key: APSCHEDULER_TIMEZONE
        value: UTC
      - key: MPLBACKEND
        value: Agg
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1

  - type: redis
    name: tradeai-redis
    plan: starter
    ipAllowList: []

databases:
  - name: tradeai-db
    plan: starter
    databaseName: tradeai_companion
    user: tradeai_user